### ISSUE TITLE
Checklist To Do

### ISSUE THREAD

**Issue by RalphHightower** [RalphHightower/blog#79]
- [ ] Create README.md
- [ ] Customize _config.yml
- [ ] Add LICENSE.txt
- [ ] Add Code of Conduct
- [ ] Add Security Policy 
- [ ] Create Issue Templates
